{% set version = "0.5.11" %}
{% set org = "pyne" %}
{% set sha256 = "ba05917b0de446ec520857655e77967a783e3bc723299faf5989f532d6b0647a" %}
{% set variant = "openblas" %}

package:
  name: pyne
  version: {{ version }}

source:
  fn: pyne-{{ version }}-{{ sha256 }}.tar.gz
  url: https://github.com/{{ org }}/pyne/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  # note that builds timeout on mac with many versions of python & numpy
  skip: True  # [win or (osx and py34)]
  detect_binary_files_with_prefix: true
  features:
    - blas_{{ variant }}

requirements:
  build:
    - cmake
    - pkg-config
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - toolchain3
    - setuptools
    - python
    - blas 1.1 {{ variant }}
    - openblas
    - boost-cpp
    - hdf5
    - bzip2
    - xz
    - moab 4.*  # [linux]
    - cython
    - numpy
    - pytables
  run:
    - python
    - blas 1.1 {{ variant }}
    - openblas
    - boost-cpp
    - hdf5
    - bzip2
    - xz
    - moab 4.*  # [linux]
    - {{ pin_compatible('numpy') }}
    - scipy
    - pytables

test:
  requires:
    - setuptools
    - nose
    - pytables
    - jinja2
  source_files:
    - pyne
    - src
    - tests

about:
  home: http://pyne.io/
  license: BSD 3-Clause
  license_file: license.txt
  summary: "The nuclear engineering toolkit"

extra:
  recipe-maintainers:
    - scopatz
