{% set name = "pyne" %}
{% set version = "0.7.0" %}
{% set build = "0" %}
{% set sha256 = "19e104a05aa56ef2e747f5e4a1c4cffefdb57a592a300823265ba72a1b55d4f3" %}

# ensure moab is defined (needed for conda-smithy recipe-lint)
{% set enable_moab = enable_moab or 'nomoab' %}

package:
  name: pyne
  version: {{ version }}

source:
  fn: pyne-{{ version }}-{{ sha256 }}.tar.gz
  url: https://github.com/{{ name }}/pyne/archive/{{ version }}-rc1.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}
  {% if enable_moab == 'moab' %}
  {% set moab_prefix = "moab" %}
  {% else %}
  {% set moab_prefix = "nomoab" %}
  {% endif %}
  string: "{{ moab_prefix }}_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ build }}"

  {% if enable_moab == 'moab' %}
  run_exports:
    - {{ name }} * {{ moab_prefix }}_*
  {% endif %}

  skip: True  # [win or (osx and py34)]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - cmake
    - pkg-config
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ compiler("fortran") }}
  host:
    - python
    - hdf5
    - numpy
    - pytables
    - cython
    - moab  # [ enable_moab = 'moab' ]
  run:
    - python
    - hdf5
    - pytables
    - numpy
    - scipy
    - future
    - jinja2
    - moab  # [ enable_moab = 'moab' ]
test:
  requires:
    - nose
  source_files:
    - pyne
    - src
    - tests

about:
  home: http://pyne.io/
  license: BSD 3-Clause
  license_file: license.txt
  summary: "The nuclear engineering toolkit"

extra:
  recipe-maintainers:
    - scopatz
    - gonuke
    - bam241
    - kkiesling
    - a-co
    - opotowsky
    - katyhuff
    - pshriwise
