{% set version = "0.5.7" %}
{% set org = "pyne" %}
{% set sha256 = "a47b87a39cae98e1d727ff6ea4d3027a479e3655e84c2b2cbf889bf57217f600" %}
{% set variant = "openblas" %}

package:
  name: pyne
  version: {{ version }}

source:
  fn: pyne-{{ version }}-{{ sha256 }}.tar.gz
  url: https://github.com/{{ org }}/pyne/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  # note that builds timeout on mac with many versions of python & numpy
  skip: True  # [win or (osx and py34)]
  detect_binary_files_with_prefix: true
  features:
    - blas_{{ variant }}

requirements:
  build:
    - toolchain
    - cmake
    - pkg-config
    - setuptools
    - gcc
    - libgcc
    - libgfortran
    - python
    - blas 1.1 {{ variant }}
    - openblas 0.2.19|0.2.19.*
    - boost-cpp 1.64.*
    - hdf5 1.8.18|1.8.18.*
    - bzip2 1.0.*
    - xz 5.2.*
    - moab
    - cython
    - numpy x.x  # [linux]
    - numpy 1.12.*  # [osx]
    - pytables
  run:
    - python
    - blas 1.1 {{ variant }}
    - openblas 0.2.19|0.2.19.*
    - boost-cpp 1.64.*
    - hdf5 1.8.18|1.8.18.*
    - bzip2 1.0.*
    - xz 5.2.*
    - moab
    - numpy x.x  # [linux]
    - numpy 1.12.*  # [osx]
    - scipy
    - pytables
    - libgcc
    - libgfortran

test:
  requires:
    - setuptools
    - nose
    - pytables
    - jinja2
  source_files:
    - pyne
    - src
    - tests

about:
  home: http://pyne.io/
  license: BSD 3-Clause
  license_file: license.txt
  summary: "The nuclear engineering toolkit"

extra:
  recipe-maintainers:
    - scopatz
