{% set org = "pyne" %}
{% set version = "0.7.5" %}
{% set build = 0 %}
# Update the SHA256: `shasum -a 256 pyne.X.Y.Z.tar.gz`
{% set sha256 = "80143d5e232b89ffd89121363c0e1e615acc28c26f5d7682521eb9baf98311c4" %}

# ensure moab is defined (needed for conda-smithy recipe-lint)
{% set enable_moab = enable_moab or 'nomoab' %}
{% set enable_openmc = enable_openmc or 'noopenmc' %}


package:
  name: pyne
  version: {{ version }}

source:
  git_url: https://github.com/pyne/pyne
  git_rev: develop


build:
  number: {{ build }}
  {% if enable_moab == 'moab' %}
  {% set moab_prefix = "moab" %}
  {% else %}
  {% set moab_prefix = "nomoab" %}
  {% endif %} 

  {% if enable_openmc == 'openmc' %}
  {% set openmc_prefix = "openmc" %}
  {% else %}
  {% set openmc_prefix = "noopenmc" %}
  {% endif %} 

  {% if enable_dagmc == 'dagmc' and enable_moab == 'moab' %}
  {% set dagmc_prefix = "dagmc" %}
  {% else %}
  {% set dagmc_prefix = "nodagmc" %}
  {% endif %} 

  string: {{ moab_prefix }}_{{ openmc_prefix }}_{{ dagmc_prefix }}py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ build }}

  skip: true  # [win or osx]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - pkg-config
    - python
    - {{ stdlib("c") }}
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ compiler("fortran") }}
    - cmake
    - make
    - libblas
    - liblapack
    - eigen
    - numpy
    - scipy
    - matplotlib-base
    - git
    - setuptools
    - pytest
    - pytables
    - jinja2    
    - cython
    - future
    - progress
    - meson
  host:
    - libblas
    - liblapack
    - python
    - eigen
    - numpy
    - scipy
    - matplotlib-base
    - git
    - setuptools
    - pytest
    - pytables
    - jinja2
    - cython
    - future
    - progress
    - meson 
    - moab  # [ enable_moab == 'moab']
  run:
    - libblas
    - liblapack
    - python
    - eigen
    - numpy
    - scipy
    - matplotlib-base
    - git
    - setuptools
    - pytest
    - pytables
    - jinja2
    - cython
    - future
    - progress
    - meson 
    - moab  # [ enable_moab == 'moab']
    - openmc  # [ enable_openmc == 'openmc']
    - dagmc  # [ dagmc_prefix == 'dagmc']
test:
  requires:
    - pytest
  source_files:
    - pyne
    - src
    - tests

about:
  home: http://pyne.io/
  license: BSD-3-Clause
  license_file: license.txt
  summary: The nuclear engineering toolkit

extra:
  recipe-maintainers:
    - scopatz
    - gonuke
    - bam241
    - kkiesling
    - opotowsky
    - bquan0
