{% set version = "0.5.10" %}
{% set org = "pyne" %}
{% set sha256 = "82f39753c6cc8d627bd66a9bef88eb4f6f2a56cf0e27c1a0700518fa6304be11" %}
{% set variant = "openblas" %}

package:
  name: pyne
  version: {{ version }}

source:
  fn: pyne-{{ version }}-{{ sha256 }}.tar.gz
  url: https://github.com/{{ org }}/pyne/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  # note that builds timeout on mac with many versions of python & numpy
  skip: True  # [win32 or (win and py34) or (win and py27) or (osx and py34)]
  detect_binary_files_with_prefix: true
  features:
    - blas_{{ variant }}

requirements:
  build:
    - toolchain3
    - cmake
    - pkg-config  # [not win]
    - setuptools
    - gcc  # [not win]
    - flang  # [win]
    - jom  # [win]
    - libgcc  # [not win]
    - libgfortran  # [not win]
    - python
    - blas 1.1 {{ variant }}
    - openblas 0.2.20|0.2.20.*
    - boost-cpp 1.65.1
    - hdf5 1.10.1
    - bzip2 1.0.*
    - xz 5.2.*
    - moab  # [linux]
    - cython
    - numpy 1.11.*
    - pytables
  run:
    - python
    - blas 1.1 {{ variant }}
    - openblas 0.2.20|0.2.20.*
    - boost-cpp 1.65.1
    - hdf5 1.10.1
    - bzip2 1.0.*
    - xz 5.2.*
    - moab
    - numpy >=1.11.*
    - scipy
    - pytables
    - libgcc
    - libgfortran

test:
  requires:
    - setuptools
    - nose
    - pytables
    - jinja2
  source_files:
    - pyne
    - src
    - tests

about:
  home: http://pyne.io/
  license: BSD 3-Clause
  license_file: license.txt
  summary: "The nuclear engineering toolkit"

extra:
  recipe-maintainers:
    - scopatz
