{% set org = "pyne" %}
{% set version = "0.7.2" %}
{% set build = "0" %}
# Update the SHA256: `shasum -a 256 pyne.X.Y.Z.tar.gz`
{% set sha256 = "9b2d3694f2879f0ec8210176887d1133344dd8831d31f94524b66126308753c9" %}

# ensure moab is defined (needed for conda-smithy recipe-lint)
{% set enable_moab = enable_moab or 'nomoab' %}
{% set enable_openmc = enable_openmc or 'noopenmc' %}


package:
  name: pyne
  version: {{ version }}

source:
  fn: pyne-{{ version }}-{{ sha256 }}.tar.gz
  url: https://github.com/{{ org }}/pyne/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}
  {% if enable_moab == 'moab' %}
  {% set moab_prefix = "moab" %}
  {% else %}
  {% set moab_prefix = "nomoab" %}
  {% endif %} 

  {% if enable_openmc == 'openmc' %}
  {% set openmc_prefix = "openmc" %}
  {% else %}
  {% set openmc_prefix = "noopenmc" %}
  {% endif %} 

  string: "{{ moab_prefix }}_{{ openmc_prefix }}py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ build }}"

  skip: True  # [win or osx]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - cmake
    - pkg-config
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ compiler("fortran") }}
  host:
    - python
    - hdf5
    - numpy
    - pytables
    - cython
    - moab  # [ enable_moab == 'moab']
  run:
    - python
    - hdf5
    - pytables
    - numpy
    - scipy
    - future
    - jinja2
    - moab  # [ enable_moab == 'moab']
    - openmc  # [ enable_openmc == 'openmc']
test:
  requires:
    - nose
  source_files:
    - pyne
    - src
    - tests

about:
  home: http://pyne.io/
  license: BSD-3-Clause
  license_file: license.txt
  summary: "The nuclear engineering toolkit"

extra:
  recipe-maintainers:
    - scopatz
    - gonuke
    - bam241
    - kkiesling
    - opotowsky
