schema_version: 1

context:
  version: "0.7.5"

package:
  name: pyne
  version: ${{ version }}

source:
  url: https://github.com/pyne/pyne/archive/${{ version }}.tar.gz
  sha256: 80143d5e232b89ffd89121363c0e1e615acc28c26f5d7682521eb9baf98311c4
  patches:
    - use-importlib.patch
    - use-setuptools._distutils.patch

build:
  number: 1
  string: ${{ moab_prefix }}_${{ openmc_prefix }}py${{ python | version_to_buildstring }}h${{ hash }}_${{ build }}
  skip:
    - win
    - osx
  prefix_detection:
    ignore_binary_files: true

requirements:
  build:
    - ${{ stdlib("c") }}
    - ${{ compiler("cxx") }}
    - ${{ compiler("fortran") }}
    - cmake
    - pkg-config
  host:
    - python
    - setuptools
    - hdf5
    - numpy
    - pytables
    - cython
    - if: enable_moab == "moab"
      then: moab
  run:
    - python
    - hdf5
    - pytables
    - numpy
    - scipy
    - future
    - jinja2
    - if: enable_moab == "moab"
      then: moab
    - if: enable_openmc == "openmc"
      then: openmc

tests:
  - package_contents:
      include:
        - pyne/pyne.h
      lib:
        - pyne
      site_packages:
        - pyne/nuc_data.h5
      files:
        - lib/libpyne*

  - files:
      source:
        - pyne
        - src
        - tests
    requirements:
      run:
        - nose
    script:
      - ${PYTHON} -c "from pyne.pyne_config import pyne_conf; print(pyne_conf.NUC_DATA_PATH)"
      - cd tests
      # It takes too long to download data files for CI
      - rm -f test_endf.py xs/test_data_source.py test_fortran.py test_data_nofile.py test_materials_library.py
      - nosetests --nocapture

about:
  license: BSD-3-Clause
  license_file: license.txt
  summary: The nuclear engineering toolkit
  homepage: https://pyne.io/
  repository: https://github.com/pyne/pyne
  documentation: https://pyne.io/

extra:
  recipe-maintainers:
    - scopatz
    - gonuke
    - bam241
    - kkiesling
    - opotowsky
