travis:
  secure:
    BINSTAR_TOKEN: IyjpbiAfQi2S+c5tyFCRSZB9Zn+rJN+yBu6iwkHTYbzQ4Cpr8pOhT8UZy8aq5fBdB+BwpWsGOCrFc0rLCVkt4Ow/Ys4a6/Z8Kq9/+S0xXcF4nIZrkYMCOGp+lMXx7suun2V+hDEvue9cOw0XxKQyN//FCutKOsP94cUDjGpJl2F16YYXFDqUKy/WMXPxPiEZSqFHWoMTnMPCkatgbVsVBKbgiH0LnaOb3h+IQwi1Bow/65H9YLfq0GNhDOATRVg9dIV0SghY3fLBpoEpMUjFqOU0vgoUL8/rb/X5LERM3pYNrLASM1K6Pu/B003jCwqpnxVMfFT8I3CSDC2vfrtNOJgnW4bpiD7nsVaic1PbmtSRG0dRqHeGjAScb6H0wGr/kvTYVrCZ6Es24dU5TwzbR3QOz93fnlvj32Y0B5VUmMXSYDIvsN5rvUOtG8+zmSYZzLFqBCfp8A3mN3Y3L0sv6kZAsmiEUUP7lun3gXqL9ACqqujWjbvuKAHQ+tr9Y5NNlLwM2dESdEmdF0geGD8t15oS7GXHQ0qg8Fc+c34dvubJfcIsJjTu3DLK8gs3D2gbE0S64FShW5vcMlsvWwEKIwymwfjSPh2magsghHFDoyhL6dEGcz8ahPCKN/oh2kcx13fOs7bTrpOsWYfIkAveYvfywIGVxdkj1h0Q0CA6CQU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
